### ISSUE TITLE
Script initialization problems

### ISSUE THREAD

**Issue by 3X3Q** [sxc2/s4wrapper#1]
Okay, so I didn't fix anything it turns out. Not sure how to do this.

Basically, a fresh first initialization of the script will run just fine every time. I'm pretty sure closing the script and reinitializing it, however, will yield a local sync directory error. It gives a runtime failure and says our local sync directory can't be found.

Maybe this has something to do with:
`21: LOCAL_SYNC_DIR="newFiles";`
Although I set the variable to "" and "Touchdown" and neither worked on the second initialization of the script. We are using "Touchdown" as our local sync directory, btw.

Also, in one instance of running the script for the first time, it created a new directory called "LOCAL_SYNC_DIR". I assume this can be solved by adding "$" before the variable name in line 65?
`65: mkdir LOCAL_SYNC_DIR;`
This probably isn't relevant to our problem, though.

Anyway, I hope some of this helps. Thanks Sophia :)

**Comment by sxc2** [comment]
95dc012050d42298f7496993e598e23bedd61a49
