### ISSUE TITLE
Script sometimes has problems running continuously overnight

### ISSUE THREAD

**Issue by 3X3Q** [sxc2/s4wrapper#2]
This is happening post- power settings change. The script appears to be running fine in the morning, but there is a new folder (call it Lynly Callaway) with only half of the total files it should have, and when you scroll up in the terminal, there's an error with reference to the half-downloaded Lynly Callaway folder. See screenshot below:

![screen shot 2015-01-20 at 1 32 03 pm](https://cloud.githubusercontent.com/assets/8482049/5831260/b6764e1a-a0e3-11e4-8638-8c17dd02b5df.png)

I'm not gonna be much help in figuring out what the problem is here. My top theory is that it malfunctions after the terminal window logs that many lines of sleeping notifications, but I really have no idea.

**Comment by 3X3Q** [comment]
Here's another screenshot of a different instance that we woke up to find the script appear to be working, but having only half-downloaded a folder (this time the folder is Laura).

![screen shot 2015-01-19 at 9 21 02 am](https://cloud.githubusercontent.com/assets/8482049/5831298/7b573226-a0e4-11e4-90e4-1bd17a3e9569.png)

I think this screenshot isn't of much use because it's too short, though. Uploading anyway.

**Comment by sxc2** [comment]
Looks like we're running into:
https://github.com/bloomreach/s4cmd/issues/18

do you want to try to introduce the exponential delay? :)
[image: Inline image 1]

**Comment by sxc2** [comment]
i added a exit code checking mechanism that i think will work around that issue..
it would be nice if they find a fix for that later, but this should help for now, since we already loop. :) 

24ab3520ba79bd1f98e305225e0841b3047baa87

thanks for picking this up :+1:
